#Config File for iRestore
#A Minecraft/Bukkit plugin made by triarry
#
#DO NOT CHANGE THIS LINE
version: 2.1
#
#triarry's github: https://github.com/triarry/iRestore
#

death-message: true
keep-inventory: true
keep-xp: true
my-pet-enabled: false
check-for-updates: true
#Choose all of the events you would like to trigger the plugin. False is off, true is on.
events:
    other:
        all: false
        tnt: false
        fire: false
        void: false
        lava: false
        cactus: false
        drowning: false
        starvation: false
        suffocation: false
        falling: false
    mobs:
        all: false
        skeleton: false
        zombie: false
        ghast: false
        witch: false
        blaze: false
        wither_skeleton: false
        wither: false
        enderdragon: false
    pvp:
        all: true
        melee: false
        bows: false
        potions: false
        tnt: false 
# Percentage of XP to remove. Must be between 0 and 99. 0 by default, to remove 0% of XP.
xp-to-remove: 0
vault:
    # Vault is required if you enable this.
    enabled: false
    # Percentage of money to steal from a player on kill. Must be between 0 and 100. 2 by default.
    money-to-steal: 2
#Do **NOT** have both the blacklist and whitelist on at the same times. Problems will occur!
blacklist:
    enabled: false
    items:
    - 266
    - 298
whitelist:
    enabled: false
    items:
    - 299
    - 300
percentage-drop:
    enabled: false
    #Percentage of items to drop. Must be between 0 and 100. 0 by default, to keep 0% of all items
    percentage: 50