#Config File for PvP Restore
#A Minecraft/Bukkit plugin made by triarry

#triarry's github: https://github.com/triarry/PvPRestore
#
#Permissions:
#
#pvprestore.info: Allows players to type /pvprestore
#pvprestore.keep: Allows players to gain full access to the mod and keep their xp and inventory on death
#pvprestore.keep.xp: Allows a player to only keep their XP
#pvprestore.keep.inventory: Allows a player to only keep their inventory
#

death-message: true
keep-inventory: true
keep-xp: true
# Percentage of XP to remove. Must be between 0 and 99. 0 by default, to remove 0% of XP.
xp-to-remove: 0
