#Config File for PvPRestore
#A Minecraft/Bukkit plugin made by triarry

#
#This config file is currently unused. To see information about the plugin,
#type /pvp_restore
#
#triarry's github: https://github.com/triarry/PvPRestore
#
#Permissions:
#
#pvprestore.info: Allows players to type /pvprestore
#pvprestore.keep: Allows players to gain full access to the mod and keep their xp and inventory on death
#