#Config File for PvP Restore
#A Minecraft/Bukkit plugin made by triarry
#
#DO NOT CHANGE THIS LINE
version: 1.6
#
#triarry's github: https://github.com/triarry/PvPRestore
#

death-message: true
keep-inventory: true
keep-xp: true
my-pet-enabled: false
check-for-updates: true
other-events:
    tnt: true
    fire: true
    void: true
    lava: true
    cactus: true
    drowning: true
    starvation: true
    suffocation: true
# Percentage of XP to remove. Must be between 0 and 99. 0 by default, to remove 0% of XP.
xp-to-remove: 0
vault:
    # Vault is required if you enable this.
    enabled: false
    # Percentage of money to steal from a player on kill. Must be between 0 and 100. 2 by default.
    money-to-steal: 2
#Do **NOT** have both the blacklist and whitelist on at the same times. Problems will occur!
blacklist:
    enabled: false
    items:
    - 266
    - 298
whitelist:
    enabled: false
    items:
    - 299
    - 300