name: iRestore
main: com.github.triarry.iRestore.iRestore
version: 1.5.0
author: triarry
softdepend: [Vault, MyPet]
commands:
    irestore:
        description: Tells the player information about this plugin.
        usage: /<command>
permissions:
    irestore.participate:
        description: Required for players to actively participate in features of the plugin.
    irestore.update:
        description: Tells the player if an update is available.
        default: false
    irestore.keep.all:
        description: Allows the player to keep all their items, armor and XP.
        children:
            irestore.keep.xp: true
            irestore.keep.inventory: true
    irestore.keep.xp:
        description: Allows the player to keep their XP.
    irestore.keep.inventory:
        description: Allows the player to keep all their items and armor.
    irestore.money.steal:
        description: Allows a player to steal another players money
    irestore.money.exempt:
        description: Overrides another player's ability to steal your money
        default: false
    irestore.events.other.all:
        description: Allows a player's inventory to be saved by all "other" events.
        default: false
        children:
            irestore.events.other.anvil: true
            irestore.events.other.cactus: true
            irestore.events.other.drowning: true
            irestore.events.other.enderpearl: true
            irestore.events.other.falling: true
            irestore.events.other.fire: true
            irestore.events.other.lava: true
            irestore.events.other.lightning: true
            irestore.events.other.magic: true
            irestore.events.other.starvation: true
            irestore.events.other.suffocation: true
            irestore.events.other.suicide: true
            irestore.events.other.tnt: true
            irestore.events.other.void: true
    irestore.events.other.anvil:
        description: Allows a player's inventory to be saved by an anvil
    irestore.events.other.cactus:
        description: Allows a player's inventory to be saved by a cactus death
    irestore.events.other.drowning:
        description: Allows a player's inventory to be saved by drowning
    irestore.events.other.enderpearl:
        description: Allows a player's inventory to be saved by enderpearl falling damage
    irestore.events.other.falling:
        description: Allows a player's inventory to be saved by falling damage
    irestore.events.other.fire:
        description: Allows a player's inventory to be saved by a fire death
    irestore.events.other.lava:
        description: Allows a player's inventory to be saved by a lava death
    irestore.events.other.lightning:
        description: Allows a player's inventory to be saved by lightning
    irestore.events.other.magic:
        description: Allows a player's inventory to be saved by a magical death (potion effects)
    irestore.events.other.starvation:
        description: Allows a player's inventory to be saved by starving
    irestore.events.other.suffocation:
        description: Allows a player's inventory to be saved by suffocating
    irestore.events.other.suicide:
        description: Allows a player's inventory to be saved by suicide
    irestore.events.other.tnt:
        description: Allows a player's inventory to be saved by a TNT death
    irestore.events.other.void:
        description: Allows a player's inventory to be saved by a void death
    irestore.events.pvp.all:
        description: Allows a player's inventory to be saved by all "pvp related" events.
        default: false
        children:
            irestore.events.pvp.bows: true
            irestore.events.pvp.melee: true
            irestore.events.pvp.potions: true
            irestore.events.pvp.tamed_wolf: true
            irestore.events.pvp.thorns: true
            irestore.events.pvp.tnt: true
    irestore.events.pvp.bows:
        description: Allows a player's inventory to be saved after getting killed by another player's bow
    irestore.events.pvp.melee:
        description: Allows a player's inventory to be saved after getting killed by another player's melee weapon
    irestore.events.pvp.potions:
        description: Allows a player's inventory to be saved after getting killed by another player's potions
    irestore.events.pvp.tamed_wolf:
        description: Allows a player's inventory to be saved by a player's wolf
    irestore.events.pvp.thorns:
        description: Allows a player's inventory to be saved after getting killed by the thorns enchantment
    irestore.events.pvp.tnt:
        description: Allows a player's inventory to be saved by a TNT death
    irestore.events.mobs.all:
        description: Allows a player's inventory to be saved by all mob related events
        default: false
        children:
            irestore.events.mobs.angry_wolf: true
            irestore.events.mobs.baby_zombie: true
            irestore.events.mobs.blaze: true
            irestore.events.mobs.cave_spider: true
            irestore.events.mobs.creeper: true
            irestore.events.mobs.enderdragon: true
            irestore.events.mobs.enderman: true
            irestore.events.mobs.ghast: true
            irestore.events.mobs.giant: true
            irestore.events.mobs.iron_golem: true
            irestore.events.mobs.magma_cube: true
            irestore.events.mobs.silverfish: true
            irestore.events.mobs.skeleton: true
            irestore.events.mobs.slime: true
            irestore.events.mobs.spider: true
            irestore.events.mobs.witch: true
            irestore.events.mobs.wither: true
            irestore.events.mobs.wither_skeleton: true
            irestore.events.mobs.zombie: true
            irestore.events.mobs.zombie_pigman: true
            irestore.events.mobs.zombie_villager: true            