name: iRestore
main: com.github.triarry.iRestore.iRestore
version: 1.4.6
author: triarry
softdepend: [Vault, MyPet]
commands:
    irestore:
        description: Tells the player information about this plugin.
        usage: /<command>
permissions:
    irestore.participate:
        description: Required for players to actively participate in features of the plugin.
        default: true
    irestore.update:
        description: Tells the player if an update is available.
        default: op
    irestore.info:
        description: Tells the player information about this plugin.
        default: true
    irestore.keep:
        description: Allows the player to keep all their items, armor and XP.
        default: true
    irestore.keep.xp:
        description: Allows the player to keep their XP.
        default: true
    irestore.keep.inventory:
        description: Allows the player to keep all their items and armor.
        default: true
    irestore.money.steal:
        description: Allows a player to steal another players money
        default: true
    irestore.money.exempt:
        description: Overrides another player's ability to steal your money
        default: op
    irestore.events.tnt:
        description: Allows a player's inventory to be saved by a TNT death
        default: true
    irestore.events.fire:
        description: Allows a player's inventory to be saved by a fire death
        default: true
    irestore.events.void:
        description: Allows a player's inventory to be saved by a void death
        default: true
    irestore.events.lava:
        description: Allows a player's inventory to be saved by a lava death
        default: true
    irestore.events.cactus:
        description: Allows a player's inventory to be saved by a cactus death
        default: true
    irestore.events.drowning:
        description: Allows a player's inventory to be saved by drowning
        default: true
    irestore.events.starvation:
        description: Allows a player's inventory to be saved by starving
        default: true
    irestore.events.suffocation:
        description: Allows a player's inventory to be saved by suffocating
        default: true
    irestore.events.falling:
        description: Allows a player's inventory to be saved by falling damage
        default: true