name: PvP Restore
main: com.github.triarry.PvPRestore.PvPRestore
version: 1.4.1
author: triarry
softdepend: [Vault, MyPet]
commands:
    pvprestore:
        description: Tells the player information about this plugin.
        usage: /<command>
permissions:
    pvprestore.participate:
        description: Required for players to actively participate in features of the plugin.
        default: true
    pvprestore.update:
        description: Tells the player if an update is available.
        default: op
    pvprestore.info:
        description: Tells the player information about this plugin.
        default: true
    pvprestore.keep:
        description: Allows the player to keep all their items, armor and XP.
        default: true
    pvprestore.keep.xp:
        description: Allows the player to keep their XP.
        default: true
    pvprestore.keep.inventory:
        description: Allows the player to keep all their items and armor.
        default: true
    pvprestore.blacklist.drop:
        description: Forces a player to drop the items described in the items section of the config
        default: true
    pvprestore.whitelist.drop:
        description: Forces a player to keep the items described in the items section of the config
        default: false
    pvprestore.money.steal:
        description: Allows a player to steal another players money
        default: true
    pvprestore.money.exempt:
        description: Overrides another player's ability to steal your money
        default: op